#!/bin/bash

# this script installs RemoteGPIO_tcpip following SetupHelper rules (https://github.com/kwindrem/SetupHelper)
#
# this script will accept the following commands on the command line:
#	setup install
#	setup uninstall

packageLogFile="/var/log/RemoteGPIO_tcpip/current"

#### following lines incorporate helper resources into this script
pkgDir=$( dirname $0 )
pkgName=$( basename $pkgDir )
pkgRoot=$( dirname $pkgDir )
if [ -e "$pkgDir/HelperResources/IncludeHelpers" ]; then
	source "$pkgDir/HelperResources/IncludeHelpers"
elif [ -e "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers" ]; then
	source "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers"
else
	echo "$pkgName: helper files not found - can't continue" | tee -a "/data/log/SetupHelper"
	exit 1
fi
#### end of lines to include helper resources

# GitHub account info - fill in as appropriate
# to include this package in SetupHelper automatic updates
packageGitHubUser="drtinaz"
packageGitHubBranch="main"

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
	echo
	echo "The RemoteGPIO_tcpip is adding external Relays and Digital Inputs"
	echo "with external box attached via ethernet port, wifi, or ap"
	echo
	standardActionPrompt
fi

#### here to do the actual work

if [ $scriptAction == 'INSTALL' ] ; then
	logMessage "++ Installing RemoteGPIO_tcpip"

	tar -xvzf /data/RemoteGPIO_tcpip/FileSets/Shared/rgpio.tar.gz -C /data

	##
	## Creating /dev/gpio links at boot so the bus services are automatically created 
	##
	ln -s /data/rgpio/conf/S90rgpio_pins.sh /etc/rcS.d/S90rgpio_pins.sh
	/data/rgpio/conf/S90rgpio_pins.sh

	logMessage "++ $packageName installed"
fi

# #### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    logMessage "++ Uninstalling RemoteGPIO_tcpip"

	
	rm /etc/rcS.d/S90rgpio_pins.sh
	rm /dev/gpio/relay_3
	rm /dev/gpio/relay_4
	rm /dev/gpio/relay_5
	rm /dev/gpio/relay_6
	rm /dev/gpio/relay_7
	rm /dev/gpio/relay_8
	rm /dev/gpio/relay_9
	rm /dev/gpio/relay_a
	
	##
		
	rm -rf /data/rgpio
	logMessage "++ $packageName uninstalled"
fi

# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript INSTALL_FILES
