#!/bin/bash

# this script installs RemoteGPIO_tcpip following SetupHelper rules (https://github.com/kwindrem/SetupHelper)
#
# this script will accept the following commands on the command line:
#	setup install
#	setup uninstall

packageLogFile="/var/log/RemoteGPIO_tcpip/current"

#### following lines incorporate SetupHelper utilities into this script
# Refer to the SetupHelper ReadMe file for details.

source "/data/SetupHelper/CommonResources"

#### end of lines to include SetupHelper

# GitHub account info - fill in as appropriate
# to include this package in SetupHelper automatic updates
packageGitHubUser="thomasinaz41213"
packageGitHubBranch="main"

restartSystemCalc=false

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
	echo
	echo "The RemoteGPIO_tcpip is adding external Relays and Digital Inputs"
	echo "with external box attached via ethernet port, wifi, or ap"
	echo
	standardActionPrompt
fi

#### here to do the actual work

if [ $scriptAction == 'INSTALL' ] ; then
	logMessage "++ Installing RemoteGPIO_tcpip"

	tar -xvzf /data/RemoteGPIO_tcpip/FileSets/Shared/rgpio.tar.gz -C /data
    
	installService $packageName

	updateActiveFile /opt/victronenergy/dbus-systemcalc-py/delegates/relaystate.py 
	updateActiveFile /etc/venus/gpio_list
	updateActiveFile /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json
	updateActiveFile /data/rgpio/conf/RemoteGPIO.json

	##
	## Creating /dev/gpio links at boot so the bus services are automatically created 
	##
	ln -s /data/rgpio/conf/S90rgpio_pins.sh /etc/rcS.d/S90rgpio_pins.sh
	/data/rgpio/conf/S90rgpio_pins.sh
	
	restartSystemCalc=true

	logMessage "++ $packageName installed"
fi

# #### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    logMessage "++ Uninstalling RemoteGPIO_tcpip"

	
	restoreActiveFile /opt/victronenergy/dbus-systemcalc-py/delegates/relaystate.py 
	restoreActiveFile /etc/venus/gpio_list
	restoreActiveFile /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json
	
	rm /etc/rcS.d/S90rgpio_pins.sh
	rm /dev/gpio/relay_3
	rm /dev/gpio/relay_4
	rm /dev/gpio/relay_5
	rm /dev/gpio/relay_6
	
	##
	
	removeService $packageName
	restartSystemCalc=true
		
	rm -r /data/rgpio
#	rm -r /data/RemoteGPIO_tcpip
	logMessage "++ $packageName uninstalled"
fi



if $filesUpdated ; then
    ##
    ## Reboot or restart the services
    ##
#    svc -d /service/dbus-systemcalc-py/ ; svc -u /service/dbus-systemcalc-py/
#    svc -d /service/gui ; svc -u /service/gui
#    svc -d /service/node-red-venus ; svc -u /service/node-red-venus
    restartGui=true
fi

if $restartSystemCalc ; then
	logMessage "restarting systemcalc"
	svc -t /service/dbus-systemcalc-py
fi

# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript

